export const ADD_PROJECT = 'ADD_PROJECT';
export const PROJECT_LOADING = 'PROJECT_LOADING';
export const PROJECT_FAILED = 'PROJECT_FAILED';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const ADD_BACKLOG_ANDSPRINT = 'ADD_BACKLOG_ANDSPRINT';